## Django + Vuejs + Nginx + MongoDB
services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - private
      - public

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - private
    volumes:
      - ./mongo:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    networks:
      - public

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django
      - frontend
    networks:
      - public
      - private

networks:
  private: {}
  public: {}
    

  
    