## Django + Vuejs + Nginx + MongoDB
services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo:6.0.20-jammy
    #volumes:
    #  - ./mongo:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 8000:80
    depends_on:
      - django
      - mongo
    
    
    

  
    